### PR TITLE
Fix socket leak(server_tcp_socket_fd_) on ConnectTCPSocket fail.

### PR DESCRIPTION
**Pull request by thunderbirds66**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vareddy** [comment]
Hi @thunderbirds66,
Thank you for your interest in AWS IoT! We will evaluate your pull request internally and merge it after we are finished testing it.
Thanks!
Varun

**Comment by thunderbirds66** [comment]
Hi @vareddy, thanks for quick review.

I think my PR is not redundant because socket will not be closed if [gethostbyname](https://github.com/aws/aws-iot-device-sdk-cpp/blob/4d7f3425e03b3fb3898eb844a647cbb07891927b/network/OpenSSL/OpenSSLConnection.cpp#L219) failed.
We are experiencing this situation in unstable 3G environment.
Thanks!
TB66

**Comment by vareddy** [comment]
Hi @thunderbirds66,
I believe you are correct. Thanks for the clarification. To make the code more consistent, could you modify your pull request to remove [these](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/OpenSSL/OpenSSLConnection.cpp#L241-L245) lines as well, so that the closing of the socket happens only on the return of `ConnectTCPSocket()`. Closing the socket twice could lead to instability as the socket made invalid after closing it once. 
After that it would be good to go.
Thanks!
Varun

**Comment by thunderbirds66** [comment]
Hi @vareddy thanks for quick reply!
I think you're right and I modified my PR.
Please review this again.
Thanks!
TB66

**Pull request merged**
