### PR TITLE
Add support for proxies

### PR DESCRIPTION
**Pull request by rapmue**
If someone is behind a proxy and want to use WebSockets, the connection should be possible. Therefor a section for proxy settings is included in the config file.
My proposed implementation uses a basic HTTP proxy with authentication. The proxy has to support CONNECT in order to accept the socket.

The data flow is as follows:

1. Socket to proxy on proxy_port is opened
2. CONNECT statement with the requested endpoint and port is sent (also credentials and keep-alive)
3. Check if the Proxy sent status code 200
4. Setup TLS as before and continue with WebSockets

I think this feature is needed, as soon as someone is behind a corporate proxy.

The main problem could be the certificate which in some cases gets replaced by the filtering proxy...

### CODE REVIEW

**Comment by chaurah** [comment]
Hi @rapmue,
   Thank you for this excellent contribution. This pull request will be merged in v1.2 release of the SDK. Please do let me know if you have any further suggestions.

Rahul

**Comment by chaurah** [comment]
This got pushed from the v1.2 release because we are still working on adding integration testing. We will push this to mainline once we have a proper test set up in our release pipeline.

Rahul

**Comment by deejvince** [comment]
Bump, when is this due to merge?

**Comment by tolysz** [comment]
Hi guys, I have re-based this PR, where is the best place to push it?

**Pull request closed without merging**
